package init;

import com.adventuretime5k.runecraft.Reference;

import adamant.Adamant_axe;
import adamant.Adamant_boots;
import adamant.Adamant_chestplate;
import adamant.Adamant_helmet;
import adamant.Adamant_hoe;
import adamant.Adamant_ingot;
import adamant.Adamant_leggings;
import adamant.Adamant_pickaxe;
import adamant.Adamant_shovel;
import adamant.Adamant_sword;
import bronze.Bronze_axe;
import bronze.Bronze_boots;
import bronze.Bronze_chestplate;
import bronze.Bronze_helmet;
import bronze.Bronze_hoe;
import bronze.Bronze_ingot;
import bronze.Bronze_leggings;
import bronze.Bronze_pickaxe;
import bronze.Bronze_shovel;
import bronze.Bronze_sword;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;
import runite.Runite_ingot;
import runite.Runite_leggings;
import runite.Runite_pickaxe;
import runite.Runite_shovel;
import runite.Runite_sword;
import runite.Runite_axe;
import runite.Runite_boots;
import runite.Runite_chestplate;
import runite.Runite_helmet;
import runite.Runite_hoe;
import mithril.Mithril_axe;
import mithril.Mithril_boots;
import mithril.Mithril_chestplate;
import mithril.Mithril_helmet;
import mithril.Mithril_hoe;
import mithril.Mithril_ingot;
import mithril.Mithril_leggings;
import mithril.Mithril_pickaxe;
import mithril.Mithril_shovel;
import mithril.Mithril_sword;
import steel.Steel_axe;
import steel.Steel_boots;
import steel.Steel_chestplate;
import steel.Steel_helmet;
import steel.Steel_hoe;
import steel.Steel_ingot;
import steel.Steel_leggings;
import steel.Steel_pickaxe;
import steel.Steel_shovel;
import steel.Steel_sword;

public class ModItems {
	
	public static Item adamant_ingot;
	public static Item adamant_axe;
	public static Item adamant_pickaxe;
	public static Item adamant_shovel;
	public static Item adamant_sword;
	public static Item adamant_leggings;
	public static Item adamant_hoe;
	public static Item adamant_boots;
	public static Item adamant_chestplate;
	public static Item adamant_helmet;
	public static Item bronze_ingot;
	public static Item bronze_axe;
	public static Item bronze_pickaxe;
	public static Item bronze_shovel;
	public static Item bronze_sword;
	public static Item bronze_leggings;
	public static Item bronze_hoe;
	public static Item bronze_boots;
	public static Item bronze_chestplate;
	public static Item bronze_helmet;
	public static Item steel_ingot;
	public static Item steel_axe;
	public static Item steel_pickaxe;
	public static Item steel_shovel;
	public static Item steel_sword;
	public static Item steel_leggings;
	public static Item steel_hoe;
	public static Item steel_boots;
	public static Item steel_chestplate;
	public static Item steel_helmet;
	public static Item mithril_ingot;
	public static Item mithril_axe;
	public static Item mithril_pickaxe;
	public static Item mithril_shovel;
	public static Item mithril_sword;
	public static Item mithril_leggings;
	public static Item mithril_hoe;
	public static Item mithril_boots;
	public static Item mithril_chestplate;
	public static Item mithril_helmet;
	public static Item runite_ingot;
	public static Item runite_axe;
	public static Item runite_pickaxe;
	public static Item runite_shovel;
	public static Item runite_sword;
	public static Item runite_leggings;
	public static Item runite_hoe;
	public static Item runite_boots;
	public static Item runite_chestplate;
	public static Item runite_helmet;
	
	public static void init() {
		adamant_ingot = new Adamant_ingot();
		adamant_axe = new Adamant_axe();
		adamant_pickaxe = new Adamant_pickaxe();
		adamant_shovel = new Adamant_shovel();
		adamant_sword = new Adamant_sword();
		adamant_leggings = new Adamant_leggings();
		adamant_hoe = new Adamant_hoe();
		adamant_boots = new Adamant_boots();
		adamant_chestplate = new Adamant_chestplate();
		adamant_helmet = new Adamant_helmet();
		bronze_ingot = new Bronze_ingot();
		bronze_axe = new Bronze_axe();
		bronze_pickaxe = new Bronze_pickaxe();
		bronze_shovel = new Bronze_shovel();
		bronze_sword = new Bronze_sword();
		bronze_leggings = new Bronze_leggings();
		bronze_hoe = new Bronze_hoe();
		bronze_boots = new Bronze_boots();
		bronze_chestplate = new Bronze_chestplate();
		bronze_helmet = new Bronze_helmet();
		steel_ingot = new Steel_ingot();
		steel_axe = new Steel_axe();
		steel_pickaxe = new Steel_pickaxe();
		steel_shovel = new Steel_shovel();
		steel_sword = new Steel_sword();
		steel_leggings = new Steel_leggings();
		steel_hoe = new Steel_hoe();
		steel_boots = new Steel_boots();
		steel_chestplate = new Steel_chestplate();
		steel_helmet = new Steel_helmet();
		mithril_ingot = new Mithril_ingot();
		mithril_axe = new Mithril_axe();
		mithril_pickaxe = new Mithril_pickaxe();
		mithril_shovel = new Mithril_shovel();
		mithril_sword = new Mithril_sword();
		mithril_leggings = new Mithril_leggings();
		mithril_hoe = new Mithril_hoe();
		mithril_boots = new Mithril_boots();
		mithril_chestplate = new Mithril_chestplate();
		mithril_helmet = new Mithril_helmet();
		runite_ingot = new Runite_ingot();
		runite_axe = new Runite_axe();
		runite_pickaxe = new Runite_pickaxe();
		runite_shovel = new Runite_shovel();
		runite_sword = new Runite_sword();
		runite_leggings = new Runite_leggings();
		runite_hoe = new Runite_hoe();
		runite_boots = new Runite_boots();
		runite_chestplate = new Runite_chestplate();
		runite_helmet = new Runite_helmet();
	}

	public static void register() {
		GameRegistry.register(adamant_ingot);
		GameRegistry.register(adamant_axe);
		GameRegistry.register(adamant_pickaxe);
		GameRegistry.register(adamant_shovel);
		GameRegistry.register(adamant_sword);
		GameRegistry.register(adamant_leggings);
		GameRegistry.register(adamant_hoe);
		GameRegistry.register(adamant_boots);
		GameRegistry.register(adamant_chestplate);
		GameRegistry.register(adamant_helmet);
		GameRegistry.register(bronze_ingot);
		GameRegistry.register(bronze_axe);
		GameRegistry.register(bronze_pickaxe);
		GameRegistry.register(bronze_shovel);
		GameRegistry.register(bronze_sword);
		GameRegistry.register(bronze_leggings);
		GameRegistry.register(bronze_hoe);
		GameRegistry.register(bronze_boots);
		GameRegistry.register(bronze_chestplate);
		GameRegistry.register(bronze_helmet);
		GameRegistry.register(steel_ingot);
		GameRegistry.register(steel_axe);
		GameRegistry.register(steel_pickaxe);
		GameRegistry.register(steel_shovel);
		GameRegistry.register(steel_sword);
		GameRegistry.register(steel_leggings);
		GameRegistry.register(steel_hoe);
		GameRegistry.register(steel_boots);
		GameRegistry.register(steel_chestplate);
		GameRegistry.register(steel_helmet);
		GameRegistry.register(mithril_ingot);
		GameRegistry.register(mithril_axe);
		GameRegistry.register(mithril_pickaxe);
		GameRegistry.register(mithril_shovel);
		GameRegistry.register(mithril_sword);
		GameRegistry.register(mithril_leggings);
		GameRegistry.register(mithril_hoe);
		GameRegistry.register(mithril_boots);
		GameRegistry.register(mithril_chestplate);
		GameRegistry.register(mithril_helmet);
		GameRegistry.register(runite_ingot);
		GameRegistry.register(runite_axe);
		GameRegistry.register(runite_pickaxe);
		GameRegistry.register(runite_shovel);
		GameRegistry.register(runite_sword);
		GameRegistry.register(runite_leggings);
		GameRegistry.register(runite_hoe);
		GameRegistry.register(runite_boots);
		GameRegistry.register(runite_chestplate);
		GameRegistry.register(runite_helmet);
	}
	
	public static void registerRender() {
		registerRender(adamant_ingot);
		registerRender(adamant_axe);
		registerRender(adamant_pickaxe);
		registerRender(adamant_shovel);
		registerRender(adamant_sword);
		registerRender(adamant_leggings);
		registerRender(adamant_hoe);
		registerRender(adamant_boots);
		registerRender(adamant_chestplate);
		registerRender(adamant_helmet);
		registerRender(bronze_ingot);
		registerRender(bronze_axe);
		registerRender(bronze_pickaxe);
		registerRender(bronze_shovel);
		registerRender(bronze_sword);
		registerRender(bronze_leggings);
		registerRender(bronze_hoe);
		registerRender(bronze_boots);
		registerRender(bronze_chestplate);
		registerRender(bronze_helmet);
		registerRender(steel_ingot);
		registerRender(steel_axe);
		registerRender(steel_pickaxe);
		registerRender(steel_shovel);
		registerRender(steel_sword);
		registerRender(steel_leggings);
		registerRender(steel_hoe);
		registerRender(steel_boots);
		registerRender(steel_chestplate);
		registerRender(steel_helmet);
		registerRender(mithril_ingot);
		registerRender(mithril_axe);
		registerRender(mithril_pickaxe);
		registerRender(mithril_shovel);
		registerRender(mithril_sword);
		registerRender(mithril_leggings);
		registerRender(mithril_hoe);
		registerRender(mithril_boots);
		registerRender(mithril_chestplate);
		registerRender(mithril_helmet);
		registerRender(runite_ingot);
		registerRender(runite_axe);
		registerRender(runite_pickaxe);
		registerRender(runite_shovel);
		registerRender(runite_sword);
		registerRender(runite_leggings);
		registerRender(runite_hoe);
		registerRender(runite_boots);
		registerRender(runite_chestplate);
		registerRender(runite_helmet);
	}
	
	private static void registerRender(Item item) {
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
	}
}
